source :gemcutter

gem "testdrive"
gem "builder"
gem "datamapper"
gem "dm-sqlite-adapter"
gem "do_sqlite3"
gem "dm-migrations"
gem "erubis"
gem "logging"
gem "mail_builder"
gem "rack"
gem "rack-test"
gem "rake"
gem "redis_directory", :git => "git@github.com:sam/redis_directory.git"
gem "uuid"